export enum TukanType {
    Action = "action",
    Atmospheric = "atmospheric",
    Card = "card",
    ColRichtext = "col-richtext",
    Contact = "contact",
    Details = "details",
    Focus = "focus",
    Footer = "footer",
    Headline = "headline",
    HeroImage = "hero-image",
    HighlightText = "highlight-text",
    ImageAndText = "image-and-text",
    ImageWithCaption = "image-with-caption",
    InfiniteCards = "infinite-cards",
    Location = "location",
    MultiFunctional = "multi-functional",
    PaypalExpressProduct = "paypal-express-product",
    Preview = "preview",
    Richtext = "richtext",
    StageBlog = "stage-blog",
    ShopifyProduct = "shopify-product",
}