# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
    - image: circleci/node:11.15.0

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: 
        name: Installing
        command: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run: 
        name: Building
        command: yarn build

    - run: 
        name: Linting
        command: yarn lint

    - run:
        name: Testing
        command: yarn test


  dev-build-and-deploy:
    docker:
    - image: circleci/node:11.15.0

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Deploy to Development
        command: yarn deploy-dev --token ${NOW_TOKEN}

  beta-build-and-deploy:
    docker:
    - image: circleci/node:11.15.0

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Deploy to Beta
        command: yarn deploy-beta --token ${NOW_TOKEN} --alex ${NOW_TOKEN_ALEXFI}

  prod-build-and-deploy:
    docker:

    - image: circleci/node:11.15.0

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Deploy to Production
        command: yarn deploy-all --token ${NOW_TOKEN}

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - dev-build-and-deploy:
          filters:
            branches:
              only: development
      - beta-build-and-deploy:
          filters:
            branches:
              only: beta
      - prod-build-and-deploy:
          filters:
            branches:
              only: master



