# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  dev-build-and-deploy:
    docker:

    - image: circleci/node:11.0.0

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run: yarn build

    - run: yarn lint

    - run:
        name: Testing
        command: yarn test

    - run:
        name: Test deployment to now
        command: yarn deploy-test --token ${NOW_TOKEN}

    prod-build-and-deploy:
      docker:

      - image: circleci/node:11.0.0

      working_directory: ~/repo

      steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

      - run: yarn lint

      - run:
          name: Testing
          command: yarn test

      - run:
          name: Deploy to production
          command: yarn deploy-all --token ${NOW_TOKEN}

workflows:
  version: 2
  build-deploy:
    jobs:
      - dev-build-and-deploy:
          filters:
            branches:
              only: development
      - prod-build-and-deploy:
          filters:
            branches:
              only: master



